### PR TITLE
Release v1.2.0 IndEAA

### PR DESCRIPTION
**Pull request by frinzekt**
See Commit history for the summary of changes made or changelog

### CODE REVIEW

**Comment by frinzekt** [comment]
This PR is waiting on #137 to be merged to develop before making a release

**Comment by MouseAndKeyboard** [comment]
All PRs open have been reviewed.

**Comment by frinzekt** [comment]
@MouseAndKeyboard  you can continue this PR. Maybe create a changelog for this release?

**Comment by frinzekt** [comment]
Note: Do NOT SQUASH AND MERGE to `main`

**Pull request merged**
